# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: clock.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""

from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC, 5, 29, 0, "", "clock.proto"
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\x0b\x63lock.proto\x12\x05\x63lock"7\n\x0c\x43lockMessage\x12\x14\n\x0clogical_time\x18\x01 \x01(\x05\x12\x11\n\tsender_id\x18\x02 \x01(\t"\x05\n\x03\x41\x63k2@\n\x0eMachineService\x12.\n\x0bSendMessage\x12\x13.clock.ClockMessage\x1a\n.clock.Ackb\x06proto3'
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, "clock_pb2", _globals)
if not _descriptor._USE_C_DESCRIPTORS:
    DESCRIPTOR._loaded_options = None
    _globals["_CLOCKMESSAGE"]._serialized_start = 22
    _globals["_CLOCKMESSAGE"]._serialized_end = 77
    _globals["_ACK"]._serialized_start = 79
    _globals["_ACK"]._serialized_end = 84
    _globals["_MACHINESERVICE"]._serialized_start = 86
    _globals["_MACHINESERVICE"]._serialized_end = 150
# @@protoc_insertion_point(module_scope)
